# =============================================================================
# ECR repository + build-and-push of the sample agent container.
#
# The AgentCore Runtime requires an ARM64 (Graviton) image. We build locally
# with podman (buildx-compatible multi-arch) and push. The build is gated by
# var.build_agent_image so reapplies don't rebuild by default.
#
# Podman is expected to be on PATH and the machine running (podman machine
# start). If neither is available, set build_agent_image = false and push the
# image out-of-band, then rerun terraform apply.
# =============================================================================

resource "aws_ecr_repository" "agent" {
  name                 = "${local.name_prefix}-hello-agent"
  image_tag_mutability = "MUTABLE"
  force_delete         = true

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name = "${local.name_prefix}-hello-agent"
  }
}

# Hash of the agent source. Changing any file triggers a rebuild + push.
# The MITM CA PEM is included so CA rotations force a new image. The PEM is
# gitignored and generated by scripts/fetch-avx-ca.sh, so guard with
# fileexists() — lets validate pass without it and lets customers deploy
# without DCF MITM trust.
locals {
  agent_src_hash = sha256(join("", [
    filesha256("${path.module}/agent/Dockerfile"),
    filesha256("${path.module}/agent/app.py"),
    filesha256("${path.module}/agent/requirements.txt"),
    fileexists("${path.module}/agent/avx-root-ca.pem") ? filesha256("${path.module}/agent/avx-root-ca.pem") : "",
  ]))

  agent_image_uri = "${aws_ecr_repository.agent.repository_url}:${var.agent_image_tag}"
}

resource "null_resource" "agent_build_push" {
  count = var.build_agent_image ? 1 : 0

  triggers = {
    src_hash = local.agent_src_hash
    image    = local.agent_image_uri
  }

  provisioner "local-exec" {
    working_dir = "${path.module}/agent"
    environment = {
      AWS_REGION = var.aws_region
      ECR_URI    = local.agent_image_uri
      ECR_HOST   = "${local.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"
    }
    command = <<-BASH
      set -euo pipefail
      aws ecr get-login-password --region "$${AWS_REGION}" \
        | podman login --username AWS --password-stdin "$${ECR_HOST}"
      podman build --platform linux/arm64 -t "$${ECR_URI}" .
      podman push "$${ECR_URI}"
    BASH
  }

  depends_on = [aws_ecr_repository.agent]
}
